### ISSUE TITLE
advice

### ISSUE THREAD

**Issue by UchihaSR** [laurenmurphyx64/laurenmurphyx64.github.io#1]
Greetings, I hope you are doing well.

I am interested in the zephyr project and C language. I would like to know how to get started if I want to contribute to the Zephyr project.  I am below average in coding but I certainly want to contribute and enhance my skills.  if you could give me some tips on how to get upskilled in c and be able to contribute to these os related projects
your feedback would be appreciated.

**Comment by laurenmurphyx64** [comment]
Hi! The best place to begin would be with the [Zephyr Project wiki's Getting Started Guide](https://docs.zephyrproject.org/latest/getting_started/index.html), which has instructions on installing Zephyr on your system and booting a Hello World Zephyr app. Although the easiest option for getting started with Zephyr is on an emulator like [QEMU](https://docs.zephyrproject.org/latest/boards/x86/qemu_x86/doc/index.html), a good beginner board is the [NXP FRDM-K64F](https://docs.zephyrproject.org/latest/boards/arm/frdm_k64f/doc/index.html). Once you feel more confident about your C programming skills, you can try taking [open and unassigned issues for beginners](https://github.com/zephyrproject-rtos/zephyr/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue%22+no%3Aassignee) on the [Zephyr Project Github repository](https://github.com/zephyrproject-rtos/zephyr). Contribution guidelines and other resources for Zephyr developers can be found in the [User and Developer Guides](https://docs.zephyrproject.org/latest/guides/index.html) on the [wiki](https://docs.zephyrproject.org/latest/index.html). You can also connect to hundreds of users and developers of Zephyr on the Zephyr mailing lists, in Slack, and elsewhere through the [Resources listing](https://docs.zephyrproject.org/latest/introduction/index.html#project-resources).
